name: ci

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flutter-version:
          - 3.16.9
          - 3.32.0
          - 3.x
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: TDesignOteam/workflows/actions/setup-flutter@test
        with:
          flutter-version: ${{ matrix.flutter-version }}
          aop-registry: true
          cache: true
      - name: tdesign-adaptation
        run: sh ./tdesign-component/init.sh

      - name: Get tdesign-flutter-generator
        uses: actions/checkout@v4
        with:
          repository: TDesignOteam/tdesign-flutter-generator
          path: ./example/tdesign-flutter-generator
         
      - name: flutter pub get
        working-directory: ./tdesign-component/example
        run: flutter pub get --verbose

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: |
           # 1. 动态生成临时测试证书（密码和信息固定，仅用于测试）
           keytool -genkey -v \
           -keystore temp_test_key.jks \
           -keyalg RSA \
           -keysize 2048 \
           -validity 365 \
           -alias test_alias \
           -dname "CN=CI-Test, OU=Test, O=Test, L=Test, ST=Test, C=CN" \
           -storepass 123456 \
           -keypass 123456 \
           -keystore ./android/app/temp_test_key.jks # 证书输出到 app 目录

           # 2. 构建测试包（通过 -P 参数传递证书信息，避免硬编码）
           flutter build apk \
           --build-type test \
           -PtestStoreFile=temp_test_key.jks \
           -PtestStorePassword=123456 \
           -PtestKeyAlias=test_alias \
           -PtestKeyPassword=123456

           #flutter build apk -t ./lib/main.dart --release


  build-ios:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        flutter-version:
          - 3.16.9
          - 3.32.0
          - 3.x
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: TDesignOteam/workflows/actions/setup-flutter@test
        with:
          flutter-version: ${{ matrix.flutter-version }}
          aop-registry: true
          cache: true

      - name: tdesign-adaptation
        run: sh ./tdesign-component/init.sh

      - name: Get tdesign-flutter-generator
        uses: actions/checkout@v4
        with:
          repository: TDesignOteam/tdesign-flutter-generator
          path: ./example/tdesign-flutter-generator
      
      - name: flutter pub get
        working-directory: ./tdesign-component/example
        run: flutter pub get --verbose

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: flutter build ios --release --no-codesign

  build-web:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flutter-version:
          - 3.16.9
          - 3.32.0
          - 3.x
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: TDesignOteam/workflows/actions/setup-flutter@test
        with:
          flutter-version: ${{ matrix.flutter-version }}
          aop-registry: true
          cache: true
      - name: tdesign-adaptation
        run: sh ./tdesign-component/init.sh

      - name: Get tdesign-flutter-generator
        uses: actions/checkout@v4
        with:
          repository: TDesignOteam/tdesign-flutter-generator
          path: ./example/tdesign-flutter-generator
      
      - name: flutter pub get
        working-directory: ./tdesign-component/example
        run: flutter pub get --verbose

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: flutter build web
